
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # ... (steps for checkout, npm install, npm run build)

      - name: Deploy to Firebase preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          # Use the correct way to reference the GITHUB_TOKEN secret
          repoToken: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_THEAIADVISORYBOARD }}' 
          # Use the Service Account JSON key stored as a GitHub Secret
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' 
          # This project ID is correct and must match the Service Account key used above.
          projectId: 'theaiadvisoryboard'
          channelId: 'preview'
          expires: 7d
