jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # ... (steps for checkout, npm install, npm run build)

      - name: Deploy to Firebase preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          # Use the default token provided by GitHub Actions
          repoToken: '${{ secrets.GITHUB_TOKEN }}' 
          # Reference the new, simple secret name
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' 
          # Target the correct, unhyphenated project ID
          projectId: 'theaiadvisoryboard'
          channelId: 'preview'
          expires: 7d
